/**
 * Themes.js — Centralized theme token definitions for SmartPlanner.
 *
 * Each theme defines:
 *   - light: all 54+ CSS variable tokens for light mode
 *   - dark:  all 54+ CSS variable tokens for dark mode
 *   - font:  the CSS font-family for this theme
 *   - label/description: i18n strings for the theme selector
 *
 * Token categories:
 *   Core surfaces: body, card, cardBorder, sidebarBg, sidebarBorder, topbarBg
 *   Typography:    text, textSecondary, textMuted
 *   Inputs:        inputBg, inputBorder
 *   Interactions:  subtleBg, hoverBg
 *   Accent:        accent, accentLight, accentText, accentHover
 *   Status:        danger/success/warning/error + Bg + Border
 *   Misc:          muted, overlay, checkboxBg, stroke, logoBg
 *   Schedule type: type-intensif, type-equilibre, type-leger (+ -fg)
 *   Day colors:    day-lundi..day-dimanche (+ -fg)
 */

export const THEMES = {
    // ─── Theme 0: Default (Indigo) ───
    default: {
        light: {
            body: '#F9FAFB', card: '#FFFFFF', cardBorder: '#E5E7EB',
            sidebarBg: '#FFFFFF', sidebarBorder: '#F3F4F6', topbarBg: '#FFFFFF',
            text: '#111827', textSecondary: '#6B7280', textMuted: '#9CA3AF',
            inputBg: '#FFFFFF', inputBorder: '#D1D5DB',
            subtleBg: '#F3F4F6', hoverBg: '#F9FAFB',
            accent: '#4F46E5', accentLight: '#EEF2FF', accentText: '#FFFFFF', accentHover: '#4338CA',
            danger: '#EF4444', dangerBg: '#FEF2F2', dangerBorder: '#FECACA',
            success: '#065F46', successBg: '#ECFDF5', successBorder: '#A7F3D0',
            warning: '#92400E', warningBg: '#FFFBEB', warningBorder: '#FDE68A',
            error: '#EF4444', errorBg: '#FEF2F2', errorBorder: '#FCA5A5',
            muted: '#9CA3AF', overlay: 'rgba(0,0,0,0.3)',
            checkboxBg: '#FFFFFF', stroke: '#D1D5DB', logoBg: '#1E1B4B',
            'type-intensif': '#FEF2F2', 'type-intensif-fg': '#EF4444',
            'type-equilibre': '#ECFDF5', 'type-equilibre-fg': '#10B981',
            'type-leger': '#EFF6FF', 'type-leger-fg': '#3B82F6',
            'day-lundi': '#FEF2F2', 'day-lundi-fg': '#EF4444',
            'day-mardi': '#ECFDF5', 'day-mardi-fg': '#10B981',
            'day-mercredi': '#FFF7ED', 'day-mercredi-fg': '#EA580C',
            'day-jeudi': '#EFF6FF', 'day-jeudi-fg': '#2563EB',
            'day-vendredi': '#F5F3FF', 'day-vendredi-fg': '#7C3AED',
            'day-samedi': '#FDF2F8', 'day-samedi-fg': '#DB2777',
            'day-dimanche': '#FEF3C7', 'day-dimanche-fg': '#D97706',
        },
        dark: {
            body: '#0B1120', card: '#1E293B', cardBorder: '#334155',
            sidebarBg: '#111827', sidebarBorder: '#1E293B', topbarBg: '#111827',
            text: '#F1F5F9', textSecondary: '#94A3B8', textMuted: '#64748B',
            inputBg: '#0B1120', inputBorder: '#334155',
            subtleBg: '#0B1120', hoverBg: '#1E293B',
            accent: '#6366F1', accentLight: '#1E1B4B', accentText: '#FFFFFF', accentHover: '#818CF8',
            danger: '#F87171', dangerBg: '#2D1215', dangerBorder: '#7F1D1D',
            success: '#6EE7B7', successBg: '#0D2818', successBorder: '#065F46',
            warning: '#FCD34D', warningBg: '#422006', warningBorder: '#92400E',
            error: '#F87171', errorBg: '#2D1215', errorBorder: '#7F1D1D',
            muted: '#64748B', overlay: 'rgba(0,0,0,0.6)',
            checkboxBg: '#0B1120', stroke: '#475569', logoBg: '#1E1B4B',
            'type-intensif': '#2D1215', 'type-intensif-fg': '#F87171',
            'type-equilibre': '#0D2818', 'type-equilibre-fg': '#6EE7B7',
            'type-leger': '#0C1929', 'type-leger-fg': '#60A5FA',
            'day-lundi': '#2D1215', 'day-lundi-fg': '#F87171',
            'day-mardi': '#0D2818', 'day-mardi-fg': '#6EE7B7',
            'day-mercredi': '#431407', 'day-mercredi-fg': '#FB923C',
            'day-jeudi': '#0C1929', 'day-jeudi-fg': '#60A5FA',
            'day-vendredi': '#1E1B4B', 'day-vendredi-fg': '#A78BFA',
            'day-samedi': '#3B0A2A', 'day-samedi-fg': '#F472B6',
            'day-dimanche': '#422006', 'day-dimanche-fg': '#FCD34D',
        },
        font: "'DM Sans', sans-serif",
        label: { fr: 'Classique', en: 'Default', ar: 'افتراضي' },
        description: { fr: 'Élégant et lisible', en: 'Elegant & readable', ar: 'أنيق وسهل القراءة' },
    },

    // ─── Theme 1: Soft Blush (Feminine) ───
    softBlush: {
        light: {
            body: '#FFF5F5', card: '#FFFFFF', cardBorder: '#FFE4E6',
            sidebarBg: '#FFF1F2', sidebarBorder: '#FECDD3', topbarBg: '#FFFFFF',
            text: '#4A2030', textSecondary: '#8B5C6B', textMuted: '#C4A0AD',
            inputBg: '#FFFFFF', inputBorder: '#FECDD3',
            subtleBg: '#FFF1F2', hoverBg: '#FFE4E6',
            accent: '#DB7F8E', accentLight: '#FFDBDA', accentText: '#FFFFFF', accentHover: '#C46B7A',
            danger: '#DC2626', dangerBg: '#FEF2F2', dangerBorder: '#FECACA',
            success: '#065F46', successBg: '#ECFDF5', successBorder: '#A7F3D0',
            warning: '#92400E', warningBg: '#FFFBEB', warningBorder: '#FDE68A',
            error: '#DC2626', errorBg: '#FEF2F2', errorBorder: '#FCA5A5',
            muted: '#C4A0AD', overlay: 'rgba(0,0,0,0.25)',
            checkboxBg: '#FFFFFF', stroke: '#FECDD3', logoBg: '#5C1A2A',
            'type-intensif': '#FFF0F0', 'type-intensif-fg': '#DB7F8E',
            'type-equilibre': '#F0FDF4', 'type-equilibre-fg': '#16A34A',
            'type-leger': '#F0F4FF', 'type-leger-fg': '#3B82F6',
            'day-lundi': '#FFF0F0', 'day-lundi-fg': '#DB7F8E',
            'day-mardi': '#F0FDF4', 'day-mardi-fg': '#16A34A',
            'day-mercredi': '#FFF7ED', 'day-mercredi-fg': '#EA580C',
            'day-jeudi': '#F0F4FF', 'day-jeudi-fg': '#3B82F6',
            'day-vendredi': '#F5F0FF', 'day-vendredi-fg': '#7C3AED',
            'day-samedi': '#FDF2F8', 'day-samedi-fg': '#DB2777',
            'day-dimanche': '#FFFBEB', 'day-dimanche-fg': '#D97706',
        },
        dark: {
            body: '#1A0D11', card: '#2D1A21', cardBorder: '#3D2530',
            sidebarBg: '#221219', sidebarBorder: '#2D1A21', topbarBg: '#221219',
            text: '#FFE4E8', textSecondary: '#C4A0AD', textMuted: '#8B5C6B',
            inputBg: '#1A0D11', inputBorder: '#3D2530',
            subtleBg: '#1A0D11', hoverBg: '#2D1A21',
            accent: '#E89DA8', accentLight: '#3D2530', accentText: '#1A0D11', accentHover: '#F0B5BD',
            danger: '#F87171', dangerBg: '#3B1518', dangerBorder: '#7F1D1D',
            success: '#6EE7B7', successBg: '#0D2818', successBorder: '#065F46',
            warning: '#FCD34D', warningBg: '#422006', warningBorder: '#92400E',
            error: '#F87171', errorBg: '#3B1518', errorBorder: '#7F1D1D',
            muted: '#8B5C6B', overlay: 'rgba(0,0,0,0.5)',
            checkboxBg: '#1A0D11', stroke: '#3D2530', logoBg: '#5C1A2A',
            'type-intensif': '#3B1518', 'type-intensif-fg': '#F87171',
            'type-equilibre': '#0D2818', 'type-equilibre-fg': '#6EE7B7',
            'type-leger': '#0C1929', 'type-leger-fg': '#60A5FA',
            'day-lundi': '#3B1518', 'day-lundi-fg': '#F87171',
            'day-mardi': '#0D2818', 'day-mardi-fg': '#6EE7B7',
            'day-mercredi': '#431407', 'day-mercredi-fg': '#FB923C',
            'day-jeudi': '#0C1929', 'day-jeudi-fg': '#60A5FA',
            'day-vendredi': '#1E1B4B', 'day-vendredi-fg': '#A78BFA',
            'day-samedi': '#3B0A2A', 'day-samedi-fg': '#F472B6',
            'day-dimanche': '#422006', 'day-dimanche-fg': '#FCD34D',
        },
        font: "'Quicksand', sans-serif",
        label: { fr: 'Douceur Rose', en: 'Soft Blush', ar: 'وردي ناعم' },
        description: { fr: 'Féminin & doux', en: 'Feminine & soft', ar: 'أنثوي وناعم' },
    },

    // ─── Theme 2: Cool Blue ───
    coolBlue: {
        light: {
            body: '#E5EDFA', card: '#FFFFFF', cardBorder: '#BBD0ED',
            sidebarBg: '#F0F4FB', sidebarBorder: '#D6E2F5', topbarBg: '#FFFFFF',
            text: '#1E2A4A', textSecondary: '#495589', textMuted: '#7087BB',
            inputBg: '#FFFFFF', inputBorder: '#A2B7E4',
            subtleBg: '#F0F4FB', hoverBg: '#E5EDFA',
            accent: '#2E3E6D', accentLight: '#E5EDFA', accentText: '#FFFFFF', accentHover: '#3A4E85',
            danger: '#DC2626', dangerBg: '#FEF2F2', dangerBorder: '#FECACA',
            success: '#065F46', successBg: '#ECFDF5', successBorder: '#A7F3D0',
            warning: '#92400E', warningBg: '#FFFBEB', warningBorder: '#FDE68A',
            error: '#DC2626', errorBg: '#FEF2F2', errorBorder: '#FCA5A5',
            muted: '#7087BB', overlay: 'rgba(0,0,0,0.25)',
            checkboxBg: '#FFFFFF', stroke: '#A2B7E4', logoBg: '#1A2744',
            'type-intensif': '#FFF0F0', 'type-intensif-fg': '#DC2626',
            'type-equilibre': '#F0FDF4', 'type-equilibre-fg': '#16A34A',
            'type-leger': '#EFF6FF', 'type-leger-fg': '#3B82F6',
            'day-lundi': '#FFF0F0', 'day-lundi-fg': '#DC2626',
            'day-mardi': '#F0FDF4', 'day-mardi-fg': '#16A34A',
            'day-mercredi': '#FFF7ED', 'day-mercredi-fg': '#EA580C',
            'day-jeudi': '#EFF6FF', 'day-jeudi-fg': '#2563EB',
            'day-vendredi': '#F5F3FF', 'day-vendredi-fg': '#7C3AED',
            'day-samedi': '#FDF2F8', 'day-samedi-fg': '#DB2777',
            'day-dimanche': '#FFFBEB', 'day-dimanche-fg': '#D97706',
        },
        dark: {
            body: '#0D1220', card: '#162036', cardBorder: '#243050',
            sidebarBg: '#111827', sidebarBorder: '#162036', topbarBg: '#111827',
            text: '#E5EDFA', textSecondary: '#A2B7E4', textMuted: '#7087BB',
            inputBg: '#0D1220', inputBorder: '#243050',
            subtleBg: '#0D1220', hoverBg: '#162036',
            accent: '#7087BB', accentLight: '#162036', accentText: '#0D1220', accentHover: '#8CA0D0',
            danger: '#F87171', dangerBg: '#2D1215', dangerBorder: '#7F1D1D',
            success: '#6EE7B7', successBg: '#0D2818', successBorder: '#065F46',
            warning: '#FCD34D', warningBg: '#422006', warningBorder: '#92400E',
            error: '#F87171', errorBg: '#2D1215', errorBorder: '#7F1D1D',
            muted: '#7087BB', overlay: 'rgba(0,0,0,0.5)',
            checkboxBg: '#0D1220', stroke: '#243050', logoBg: '#1A2744',
            'type-intensif': '#2D1215', 'type-intensif-fg': '#F87171',
            'type-equilibre': '#0D2818', 'type-equilibre-fg': '#6EE7B7',
            'type-leger': '#0C1929', 'type-leger-fg': '#60A5FA',
            'day-lundi': '#2D1215', 'day-lundi-fg': '#F87171',
            'day-mardi': '#0D2818', 'day-mardi-fg': '#6EE7B7',
            'day-mercredi': '#431407', 'day-mercredi-fg': '#FB923C',
            'day-jeudi': '#0C1929', 'day-jeudi-fg': '#60A5FA',
            'day-vendredi': '#1E1B4B', 'day-vendredi-fg': '#A78BFA',
            'day-samedi': '#3B0A2A', 'day-samedi-fg': '#F472B6',
            'day-dimanche': '#422006', 'day-dimanche-fg': '#FCD34D',
        },
        font: "'Inter', sans-serif",
        label: { fr: 'Bleu Serein', en: 'Cool Blue', ar: 'أزرق هادئ' },
        description: { fr: 'Calme & moderne', en: 'Calm & modern', ar: 'هادئ وعصري' },
    },

    // ─── Theme 3: Lavender Teal ───
    lavenderTeal: {
        light: {
            body: '#FFEBED', card: '#FFFFFF', cardBorder: '#F6D5D6',
            sidebarBg: '#FFF5F5', sidebarBorder: '#F6D5D6', topbarBg: '#FFFFFF',
            text: '#27153D', textSecondary: '#5A4670', textMuted: '#9A8AAE',
            inputBg: '#FFFFFF', inputBorder: '#F6D5D6',
            subtleBg: '#FFF5F5', hoverBg: '#FFEBED',
            accent: '#3E828E', accentLight: '#E8F4F5', accentText: '#FFFFFF', accentHover: '#34707B',
            danger: '#DC2626', dangerBg: '#FEF2F2', dangerBorder: '#FECACA',
            success: '#065F46', successBg: '#ECFDF5', successBorder: '#A7F3D0',
            warning: '#92400E', warningBg: '#FFFBEB', warningBorder: '#FDE68A',
            error: '#DC2626', errorBg: '#FEF2F2', errorBorder: '#FCA5A5',
            muted: '#9A8AAE', overlay: 'rgba(0,0,0,0.25)',
            checkboxBg: '#FFFFFF', stroke: '#F6D5D6', logoBg: '#1E0E30',
            'type-intensif': '#FFF0F0', 'type-intensif-fg': '#DC2626',
            'type-equilibre': '#E8F5EE', 'type-equilibre-fg': '#16A34A',
            'type-leger': '#E8F4F5', 'type-leger-fg': '#3E828E',
            'day-lundi': '#FFF0F0', 'day-lundi-fg': '#DC2626',
            'day-mardi': '#E8F5EE', 'day-mardi-fg': '#16A34A',
            'day-mercredi': '#FFF7ED', 'day-mercredi-fg': '#EA580C',
            'day-jeudi': '#E8F4F5', 'day-jeudi-fg': '#3E828E',
            'day-vendredi': '#F5F0FF', 'day-vendredi-fg': '#7C3AED',
            'day-samedi': '#FDF2F8', 'day-samedi-fg': '#DB2777',
            'day-dimanche': '#FFFBEB', 'day-dimanche-fg': '#D97706',
        },
        dark: {
            body: '#120A18', card: '#1E1228', cardBorder: '#2D1E3A',
            sidebarBg: '#180E22', sidebarBorder: '#1E1228', topbarBg: '#180E22',
            text: '#F0E4F4', textSecondary: '#C4B4D4', textMuted: '#8A789E',
            inputBg: '#120A18', inputBorder: '#2D1E3A',
            subtleBg: '#120A18', hoverBg: '#1E1228',
            accent: '#5CAAB8', accentLight: '#1E1228', accentText: '#120A18', accentHover: '#72BCC8',
            danger: '#F87171', dangerBg: '#3B1520', dangerBorder: '#7F1D1D',
            success: '#6EE7B7', successBg: '#0D2818', successBorder: '#065F46',
            warning: '#FCD34D', warningBg: '#422006', warningBorder: '#92400E',
            error: '#F87171', errorBg: '#3B1520', errorBorder: '#7F1D1D',
            muted: '#8A789E', overlay: 'rgba(0,0,0,0.5)',
            checkboxBg: '#120A18', stroke: '#2D1E3A', logoBg: '#1E0E30',
            'type-intensif': '#3B1520', 'type-intensif-fg': '#F87171',
            'type-equilibre': '#0D2818', 'type-equilibre-fg': '#6EE7B7',
            'type-leger': '#0C1929', 'type-leger-fg': '#60A5FA',
            'day-lundi': '#3B1520', 'day-lundi-fg': '#F87171',
            'day-mardi': '#0D2818', 'day-mardi-fg': '#6EE7B7',
            'day-mercredi': '#431407', 'day-mercredi-fg': '#FB923C',
            'day-jeudi': '#0C1929', 'day-jeudi-fg': '#60A5FA',
            'day-vendredi': '#1E1B4B', 'day-vendredi-fg': '#A78BFA',
            'day-samedi': '#3B0A2A', 'day-samedi-fg': '#F472B6',
            'day-dimanche': '#422006', 'day-dimanche-fg': '#FCD34D',
        },
        font: "'Poppins', sans-serif",
        label: { fr: 'Lavande Turquoise', en: 'Lavender Teal', ar: 'لافندر فيروزي' },
        description: { fr: 'Artistique & frais', en: 'Artistic & fresh', ar: 'فنّي ومنعش' },
    },
};

export const THEME_KEYS = Object.keys(THEMES);
